version: '3'

services:
  r_umpire:
    build:
      context: r_tennis
    environment:
      - VERBOSE=1
    depends_on:
      - redis
    command: Rscript umpire.r
    volumes:
    - ./r_tennis:/app/r_tennis
  r_ball_1:
    build:
      context: r_tennis
    environment:
      - VERBOSE=1
    depends_on:
      - redis
    command: Rscript ball.r
    volumes:
    - ./r_tennis:/app/r_tennis
  r_player_1:
    build:
      context: r_tennis
    environment:
      - MYNUMBER=1
      - VERBOSE=1
    depends_on:
      - redis
    command: Rscript player.r
    volumes:
    - ./r_tennis:/app/r_tennis
  r_player_2:
    build:
      context: r_tennis
    environment:
      - MYNUMBER=2
      - VERBOSE=1
    depends_on:
      - redis
    command: Rscript player.r
    volumes:
    - ./r_tennis:/app/r_tennis
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  http_server:
    build:
      context: node_tennis
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - NODE_PATH=/usr/local/lib/node_modules
    volumes:
    - ./node_server:/app/node_server
