version: '3'

services:
  r_umpire:
    build:
      context: r_tennis
    environment:
      - VERBOSE=1
    depends_on:
      - redis
    command: Rscript umpire.r
    volumes:
    - ./r_tennis:/app/r_tennis
  go_ball_1:
    build:
      context: go_tennis
    environment:
      - VERBOSE=1
    depends_on:
      - redis
    command: go run ball.go
    volumes:
    - ./go_tennis:/app/go_tennis
  r_player_1:
    build:
      context: r_tennis
    environment:
      - MYNUMBER=1
      - VERBOSE=0
    depends_on:
      - redis
    command: Rscript player.r
    volumes:
    - ./r_tennis:/app/r_tennis
  python_player_2:
    build:
      context: python_tennis
    environment: 
      - MYNUMBER=2
      - VERBOSE=1
    depends_on:
      - redis
    command: python player.py
    volumes:
    - ./python_tennis:/app/python_tennis
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  http_server:
    build:
      context: node_tennis
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - NODE_PATH=/usr/local/lib/node_modules
    volumes:
    - ./node_tennis:/app/node_server
